apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-generator
  namespace: default
spec:
  generators:
  - git:
      repoURL: https://github.com/hazemhashem/observability.git
      revision: main
      directories:
      - path: Helm/*
      - path: Helm/promtail
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hazemhashem/observability.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
