apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-generator
  namespace: default
spec:
  generators:
  - git:
      repoURL: https://github.com/hazemhashem/observability.git
      revision: main
      directories:
      - path: Helm/*
        #- path: Helm/promtail
        # exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hazemhashem/observability.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - '{{ if eq .path "Helm/loki" }}Helm/loki/custom-values.yaml{{ end }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if eq .path "Helm/loki" }}loki{{ else if eq .path "Helm/promtail" }}loki{{ else }}{{path.basename}}{{ end }}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
